# Autogenerated wrapper script for Ncurses_jll for x86_64-apple-darwin
export libform, libmenu, libncurses, libpanel

using Gettext_jll
JLLWrappers.@generate_wrapper_header("Ncurses")
JLLWrappers.@declare_library_product(libform, "@rpath/libformw.6.dylib")
JLLWrappers.@declare_library_product(libmenu, "@rpath/libmenuw.6.dylib")
JLLWrappers.@declare_library_product(libncurses, "@rpath/libncursesw.6.dylib")
JLLWrappers.@declare_library_product(libpanel, "@rpath/libpanelw.6.dylib")
function __init__()
    JLLWrappers.@generate_init_header(Gettext_jll)
    JLLWrappers.@init_library_product(
        libform,
        "lib/libform.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmenu,
        "lib/libmenu.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libncurses,
        "lib/libncurses.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpanel,
        "lib/libpanel.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
