# Autogenerated wrapper script for Ncurses_jll for x86_64-w64-mingw32
export libform, libmenu, libncurses, libpanel

JLLWrappers.@generate_wrapper_header("Ncurses")
JLLWrappers.@declare_library_product(libform, "libform6.dll")
JLLWrappers.@declare_library_product(libmenu, "libmenu6.dll")
JLLWrappers.@declare_library_product(libncurses, "libncurses6.dll")
JLLWrappers.@declare_library_product(libpanel, "libpanel6.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libform,
        "bin\\libform6.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmenu,
        "bin\\libmenu6.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libncurses,
        "bin\\libncurses6.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpanel,
        "bin\\libpanel6.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
